apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: admin
  namespace: default
spec:
  maxReplicas: 9
  minReplicas: 3
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: admin
  targetCPUUtilizationPercentage: 60
